# Generated by Django 6.0 on 2026-01-06 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "match_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_date", models.DateField()),
                ("opponent", models.CharField(max_length=100)),
                ("venue", models.CharField(blank=True, max_length=100)),
                ("result", models.CharField(blank=True, max_length=20)),
                ("score_mfc", models.IntegerField(blank=True, null=True)),
                ("score_opponent", models.IntegerField(blank=True, null=True)),
                ("season", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "player_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("position", models.CharField(blank=True, max_length=50)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("height_cm", models.IntegerField(blank=True, null=True)),
                ("weight_kg", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("minute", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("season", models.CharField(blank=True, max_length=20)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="adminpanel.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="adminpanel.player",
                    ),
                ),
            ],
        ),
    ]
