# Generated by Django 6.0.1 on 2026-01-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_matchevent_description_matchevent_season"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="id",
        ),
        migrations.RemoveField(
            model_name="player",
            name="id",
        ),
        migrations.AddField(
            model_name="match",
            name="players",
            field=models.ManyToManyField(
                blank=True, related_name="matches", to="adminpanel.player"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_id",
            field=models.CharField(
                editable=False, max_length=20, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="player_id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
    ]
