"""Add match_time, opponent, location, and outcome to Match model

Generated by hand for project.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_match_id_remove_player_id_match_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='outcome',
            field=models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
