# Generated by Django 6.0.1 on 2026-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0004_add_match_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="league",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BFL", "Botswana Football League"),
                    ("BPL", "Botswana Premier League"),
                ],
                default="BPL",
                max_length=10,
            ),
        ),
    ]
