import os
import csv as _csv
from django.core.management.base import BaseCommand
from adminpanel.models import Player

class Command(BaseCommand):
    help = 'Import players from a CSV file (idempotent)'

    def add_arguments(self, parser):
        parser.add_argument('csv_file', type=str, help='players.csv')
        parser.add_argument('--ignore-ids', action='store_true', help='Ignore Player_ID from CSV and generate new ones; write mapping to adminpanel/mappings/players_map.csv')

    def handle(self, *args, **kwargs):
        csv_file = kwargs['csv_file']
        ignore_ids = kwargs.get('ignore_ids')
        mapping = []
        with open(csv_file, newline='', encoding='utf-8') as f:
            reader = _csv.DictReader(f)
            for row in reader:
                if ignore_ids:
                    # create new player (player_id auto-generated by model)
                    p = Player(first_name=row.get('First_Name', ''), surname=row.get('Surname', ''), position=row.get('Position', ''), height_cm=int(row.get('Height', 0)) if row.get('Height') else None)
                    p.save()
                    mapping.append({'old_id': row.get('Player_ID'), 'new_id': p.player_id})
                else:
                    Player.objects.update_or_create(
                        player_id=row.get('Player_ID'),
                        defaults={
                            'first_name': row.get('First_Name', ''),
                            'surname': row.get('Surname', ''),
                            'position': row.get('Position', ''),
                            'height_cm': int(row.get('Height', 0)) if row.get('Height') else None,
                        }
                    )

        # write mapping file if required
        if ignore_ids and mapping:
            os.makedirs(os.path.join('adminpanel', 'mappings'), exist_ok=True)
            map_path = os.path.join('adminpanel', 'mappings', 'players_map.csv')
            with open(map_path, 'w', newline='', encoding='utf-8') as mf:
                w = _csv.DictWriter(mf, fieldnames=['old_id', 'new_id'])
                w.writeheader()
                for r in mapping:
                    w.writerow(r)
            self.stdout.write(self.style.SUCCESS(f'Players imported and mapping written to {map_path}'))
        else:
            self.stdout.write(self.style.SUCCESS('Players imported successfully!'))
